print 'Some shortcuts given below -->'
print '\n'
print ':Telescope colorscheme'
print '\n'
print '<C-w>+v splits screen vertically'
print '<C-w>+s splits screen vertically'
print '<C-w><C-w> toggle screen'
print '\n'
print 'g? shows options in NvimTree'
print '\n'
print '<leader>sh [S]earch [H]elp'
print '<leader>sk [S]earch [K]eymaps'
print '<leader>sf [S]earch [F]iles'
print '<leader>ss [S]earch [S]elect Telescope'
print '<leader>sw [S]earch current [W]ord'
print '<leader>sg [S]earch by [G]rep'
print '<leader>sd [S]earch [D]iagnostics'
print '<leader>sr [S]earch [R]esume'
print '<leader>s. [S]earch Recent Files ("." for repeat)'
print '<leader><leader> [ ] Find existing buffers'
